//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 FernflowerUIMFC.rc 使用
//
#define IDD_WAITBAR                     9
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW                    101
#define IDD_SPLASHFORM                  101
#define IDD_PROGRESSBAR                 103
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDS_FILE_VIEW                   126
#define IDS_CAPTION_TEXT                127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDS_PROPERTIES_WND              129
#define IDR_FernflowerUITYPE            130
#define ID_WINDOW_MANAGER               131
#define IDS_CAPTION_IMAGE_TEXT          132
#define IDS_CAPTION_IMAGE_TIP           133
#define ID_VIEW_CLASSVIEW               134
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_OUTPUT_POPUP                182
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDR_FernflowerUITYPE1           201
#define IDR_FernflowerUITYPE_EN         201
#define IDR_MAINFRAME1                  202
#define IDR_MAINFRAME_EN                202
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define ID_START_PROGRESS               310
#define ID_DOPROGRESS                   311
#define ID_TIMER_DOPROGRESS             317
#define ID_EDITWINDOW                   318
#define ID_CLIPBOARDER                  319
#define ID_VIEW_FILEVIEW                320
#define ID_SHELLTREE                    321
#define ID_VIEW_CAPTION_BAR             323
#define ID_LINEBOX                      324
#define IDR_MENU1                       326
#define ID_VIEW_PROPERTIESWND           326
#define IDI_FILE_VIEW_HC                327
#define IDI_FILE_VIEW                   328
#define ID_STARTUPFILE_OPEN             328
#define IDD_LAUNCHBAR                   329
#define ID_INDICATOR_LINE               329
#define IDD_LAUNCHBAR1                  330
#define IDD_WAITLAUNCH                  330
#define ID_INDICATOR_COLUMN             330
#define IDD_DECOMPLIEBAR                331
#define IDR_TOOLBAR1                    336
#define IDR_MENU_IMAGES                 336
#define IDB_MENU_IMAGES_24              338
#define IDB_BITMAP1                     339
#define IDD_OPINIONBOX                  343
#define IDD_SYSINFOBOX                  343
#define IDI_PROPERTIES_WND              345
#define IDI_PROPERTIES_WND1             346
#define IDI_PROPERTIES_WND_HC           346
#define IDB_STARTLISTIMAGE              356
#define IDB_STARTLIST_IMAGE             356
#define IDR_POPUP_ALERTWND              357
#define IDD_DIALOG1                     360
#define IDC_MFCLINK1                    1001
#define IDC_MFCEDITBROWSE1              1002
#define IDC_HELP_CORE                   1002
#define IDC_PROGRESS1                   1003
#define IDC_ANIMATE1                    1006
#define IDC_BUTTON2                     1008
#define IDC_BUTTON1                     1008
#define ID_MESSAGE_NOTICE               1011
#define IDC_GROUPTITLE                  1012
#define IDC_LAUNCHTEXT                  1013
#define IDC_BUTTON4                     1016
#define IDC_CANCELBUTTON                1016
#define IDC_TREEOPINIONS                1020
#define IDC_OPINIONTIP                  1021
#define IDC_OPINIONNAME                 1022
#define IDC_COMBO2                      1024
#define IDC_CHOOSEAREA                  1024
#define IDC_COMBO1                      1025
#define IDC_LIST1                       1030
#define IDC_RECENT_FILES                1032
#define IDC_GET_STARTED                 1045
#define IDC_RECENT                      1046
#define IDC_MFCLINK2                    1048
#define IDC_OPENTASK                    1049
#define IDC_VERSIONINFO                 1050
#define IDM_OPEN_JAR                    1060
#define IDM_OPEN_CLASS                  1061
#define IDC_HELP_FEATURES               1062
#define IDC_VIEW_UPDATELOG              1063
#define IDC_SYSINFOEDIT                 1063
#define IDC_EDIT1                       1064
#define IDD_FINDTEXTBOX                 1540
#define ID_APP_TEST                     32772
#define ID_BUTTON2                      32773
#define IDR_POPUP_SHELLVIEW             32777
#define ID_POPCOM_DECOMPLIE             32779
#define ID_ENABLE_RECOVERY              32781
#define ID_ENABLE_RECOVERY2             32782
#define ID_SELECT_FONT                  32789
#define ID_CLEAR_CACHE                  32791
#define ID_QUICK_DECOMP                 32794
#define ID_FILE_                        32798
#define ID_FILE_32800                   32800
#define IDB_INFO                        32810
#define ID_WINDOW_RESET                 32811
#define ID_FILE_CLOSEFILE               32814
#define ID_FILE_SAVE32817               32817
#define ID_AUTO_SAVE                    32822
#define ID_CLASSES_INSIDE_JAR           32823
#define ID_DECOMP_OPINIONS              32828
#define ID_SETTINGS_DECOMPILE           32829
#define ID_SETTINGS_DECOMPILEOPINIONS   32830
#define ID_IGNORE_CACHE                 32834
#define ID_SETTINGS_IGNORECACHEDATA     32835
#define ID_FILE_MRU_FILELIST            32837
#define ID_FILE_RECENTLYOPENEDFILES     32844
#define ID_FILE_RECENTLYOPENEDFILES32845 32845
#define ID_FILE_SAVE32846               32846
#define ID_FILE_SAVEAS                  32847
#define ID_FILE_CLOSEFILE32848          32848
#define ID_32853                        32853
#define ID_OPENSTARTUP                  32854
#define ID_FILE_STARTUPPAGE             32855
#define ID_OPENSTARTPAGE                32856
#define ID_32857                        32857
#define ID_OPEN_MAINWND                 32858
#define ID_32859                        32859
#define ID_ENABLE_ALERTWND              32860
#define ID_SETTINGS_INFORMWHENFINISHED  32861
#define ID_32862                        32862
#define ID_SAVEMDISTATE                 32863
#define ID_32864                        32864
#define ID_32865                        32865
#define ID_REPORT_BUG                   32866
#define ID_FILE_OPEN2                   57602
#define ID_FILE_CLOSE2                  57603
#define ID_FILE_SAVE2                   57604
#define ID_FILE_SAVE_AS2                57605
#define ID_WINDOW_CLOSE                 0xE13A

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        362
#define _APS_NEXT_COMMAND_VALUE         32867
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           331
#endif
#endif
